const STOPWORDS = new Set([
  "de",
  "da",
  "do",
  "das",
  "dos",
  "e",
  "em",
  "para",
  "por",
  "com",
  "a",
  "o",
])

function stripAccents(value: string): string {
  return value.normalize("NFD").replace(/\p{M}/gu, "")
}

function tokenize(normalized: string): string[] {
  return normalized.split(/[^\p{L}\p{N}]+/u).filter((token) => token.length > 0)
}

export function generateProductCode(name: string): string {
  const tokens = tokenize(stripAccents(name.trim()))
  const significant: string[] = []
  const numbers: string[] = []

  for (const token of tokens) {
    if (/^[0-9]+$/.test(token)) {
      numbers.push(token)
      continue
    }

    if (STOPWORDS.has(token.toLowerCase())) {
      continue
    }

    significant.push(token.toUpperCase())
  }

  const numeric = numbers.join("")
  let letters = ""
  if (significant.length === 1) {
    letters = (significant[0] ?? "").slice(0, 3)
  } else if (significant.length > 1) {
    letters = significant.map((word) => word[0] ?? "").join("")
  }

  if (letters.length === 0) {
    return numeric
  }

  if (numeric.length === 0) {
    return letters
  }

  return `${letters}-${numeric}`
}

export function nextAutoGeneratedProductCode(options: {
  name: string
  codeManuallyEdited: boolean
  preservePersistedCode: boolean
}): string | null {
  if (options.preservePersistedCode || options.codeManuallyEdited) {
    return null
  }

  return generateProductCode(options.name)
}
