import { describe, expect, it } from "vitest"

import {
  generateProductCode,
  nextAutoGeneratedProductCode,
} from "@/features/catalog/lib/generateProductCode"

describe("generateProductCode", () => {
  it("uses first letters plus a numeric suffix and ignores stopwords", () => {
    expect(generateProductCode("Dobradiça de Scanner Canon 1643")).toBe(
      "DSC-1643",
    )
    expect(generateProductCode("Monitor Dell 24")).toBe("MD-24")
    expect(generateProductCode("Mesa de Reunião Grande")).toBe("MRG")
    expect(generateProductCode("Ar Condicionado 12000")).toBe("AC-12000")
    expect(generateProductCode("Cadeira de Praia 2000")).toBe("CP-2000")
  })

  it("uses up to three letters for a single significant word", () => {
    expect(generateProductCode("Cabide")).toBe("CAB")
    expect(generateProductCode("Notebook")).toBe("NOT")
    expect(generateProductCode("Projetor")).toBe("PRO")
    expect(generateProductCode("TV")).toBe("TV")
  })

  it("normalizes accents, extra spaces, hyphens, and other punctuation", () => {
    expect(generateProductCode("  Mesa   de   Reunião   Grande  ")).toBe("MRG")
    expect(generateProductCode("Ar-Condicionado 12000")).toBe("AC-12000")
    expect(generateProductCode("Cadeira, de Praia 2000")).toBe("CP-2000")
    expect(generateProductCode("Dobradiça")).toBe("DOB")
  })

  it("keeps numbers-only names without a dangling hyphen", () => {
    expect(generateProductCode("12000")).toBe("12000")
    expect(generateProductCode("de 12000")).toBe("12000")
    expect(generateProductCode("de da do")).toBe("")
    expect(generateProductCode("")).toBe("")
    expect(generateProductCode("   ---  ")).toBe("")
  })
})

describe("nextAutoGeneratedProductCode", () => {
  it("regenerates from the name until the code is edited manually", () => {
    expect(
      nextAutoGeneratedProductCode({
        name: "Monitor Dell 24",
        codeManuallyEdited: false,
        preservePersistedCode: false,
      }),
    ).toBe("MD-24")

    expect(
      nextAutoGeneratedProductCode({
        name: "Notebook",
        codeManuallyEdited: true,
        preservePersistedCode: false,
      }),
    ).toBeNull()
  })

  it("never replaces a persisted code in edit mode", () => {
    expect(
      nextAutoGeneratedProductCode({
        name: "Notebook",
        codeManuallyEdited: false,
        preservePersistedCode: true,
      }),
    ).toBeNull()
  })
})
